### PR TITLE
added rabbitfarm perl journal

### PR DESCRIPTION
**Pull request by adamcrussell**
adding a journal I write. I add one or two perl related articles a week, mostly around perl weekly challenge but often other perl topics as well.

### CODE REVIEW

**Comment by davorg** [comment]
Looks like the h1s in your feed are being rendered slightly strangely on Planet Perl. I'll see if I have time to investigate further over the next couple of days.

**Comment by adamcrussell** [comment]
Oh! That is strange. If there is anything I can do to fix this let me know, but I am not sure what the solution might be. I was in the midst of improving the styling anyway so perhaps a change I was about to make anyway could help this too.

**Comment by davorg** [comment]
I think, perhaps, just remove the HTML tags from the title on the items in the RSS feed. If you look at other RSS feeds that the site uses, you'll see that the title is just a text string.

**Comment by adamcrussell** [comment]
I have just made that change. I think you are right and hopefully that should clear it up!
________________________________

**Pull request merged**
