### PR TITLE
perlanetrc: Add StackOverflow

### PR DESCRIPTION
**Pull request by rwp0**
Perl questions at StackOverflow programming Q&A website: https://stackoverflow.com/questions/tagged/perl

### CODE REVIEW

**Comment by davorg** [comment]
It looks to me like this has the `web:` and `url:` data mixed up. Can you check it, please?

**Comment by rwp0** [comment]
Sorry, correcting.

PS: wish `url` could be named `feed` instead :-)

**Comment by davorg** [comment]
You're right. `url` is a confusing name. I'll raise an issue and add `feed` as an alias (and then, slowly deprecate `url`).

**Comment by davorg** [comment]
See https://github.com/davorg/perlanet/issues/18

**Pull request merged**
