### PR TITLE
perlanetrc: Add Emacs and Vim modelines

### PR DESCRIPTION
**Pull request by rwp0**
To enable GitHub (and editor) syntax highlighting

### CODE REVIEW

**Comment by rwp0** [comment]
@davorg why not merge this as well (for improving main code readability)?

I can create individual PR's for Emacs and Vim modelines (top and bottom) if needed.

**Comment by davorg** [comment]
I'm not a fan of adding unnecessary scaffolding like that to my files. I use VS-Code and that recognises YAML files without clues like this.

**Comment by rwp0** [comment]
> I'm not a fan of adding unnecessary scaffolding like that to my files. I use VS-Code and that recognises YAML files without clues like this.

Okay. That was mainly for GitHub (ie. for this repository's public interface).

**Comment by davorg** [comment]
Oh. Now, that's interesting. Does that work? Why doesn't it work, for example, here?

https://github.com/davorg/feeds/blob/main/Feeds/config.yml

**Comment by davorg** [comment]
Doesn't seem to make a difference.

https://github.com/davorg/planetperl/blob/master/perlanetrc

What am I missing?

**Comment by rwp0** [comment]
It works perfectly for me now.

Clearing the browser cache might help I believe.

image

**Comment by rwp0** [comment]
While it didn't get highlighted [before](https://github.com/davorg/planetperl/blob/816ed42820c63930fb9005125774e3b552805a46/perlanetrc) without a modeline:

image

Btw that's how GitHub's [Linguist](https://github.com/github/linguist) works if there's no file extension (suffix) provided.

**Pull request merged**
